/**:
  ros__parameters:
    filter1:
      name: drop_near_points
      type: laser_filters/LaserScanRangeFilter
      params:
        use_message_range_limits: false
        lower_threshold: 0.06
        upper_threshold: 100.0
        lower_replacement_value: .inf
        upper_replacement_value: .inf
