/**:
    ros__parameters:
      registration_method: "NDT_OMP"
      score_threshold: 2.0
      ndt_resolution: 2.0
      ndt_step_size: 0.1
      ndt_num_threads: 4
      ndt_max_iterations: 35
      transform_epsilon: 0.01
      voxel_leaf_size: 1.0
      scan_max_range: 100.0
      scan_min_range: 1.0
      scan_period: 0.02
      use_pcd_map: true
      map_path: "/home/curious/sick_ws/src/sick_wagen_workspace2/sick_wagen/maps/sick_10f.pcd"
      set_initial_pose: true
      initial_pose_x: 0.0
      initial_pose_y: 0.0
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.0
      initial_pose_qw: 0.0
      use_odom: false
      odom_topic: "/whill/odom"
      use_imu: true
      imu_topic: "/wit/imu"
      enable_debug: true
      enable_map_odom_tf: true
      global_frame_id: map
      odom_frame_id: odom
      base_frame_id: base_link