/ros2_laser_scan_merger:
  ros__parameters:
    flip1: false
    flip2: false
    inverse1: false
    inverse2: false
    laser1Alpha: 48.586
    laser1AngleMax: 180.0
    laser1AngleMin: -180.0
    laser1B: 0
    laser1G: 0
    laser1R: 255
    laser1XOff: 0.0
    laser1YOff: 0.29
    laser1ZOff: 0.075
    laser2Alpha: -48.586
    laser2AngleMax: 180.0
    laser2AngleMin: -180.0
    laser2B: 255
    laser2G: 0
    laser2R: 0
    laser2XOff: 0.0
    laser2YOff: -0.29
    laser2ZOff: 0.075
    pointCloudTopic: merged_cloud
    pointCloudFrameId: laser_link
    qos_overrides./parameter_events.publisher.depth: 1000
    # qos_overrides./parameter_events.publisher.durability: volatile
    # qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: best_effort
    scanTopic1: /sick_tim_L/sick_tim_5xx/scan
    scanTopic2: /sick_tim_R/sick_tim_5xx/scan
    show1: true
    show2: true
    use_sim_time: false

/pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.00087
    # angle_max: 1.5708
    # angle_min: -1.5708
    angle_max: 3.14
    angle_min: -3.14
    inf_epsilon: 1.0
    max_height: 1.0
    min_height: 0.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          # durability: volatile
          # history: keep_last
          reliability: best_effort
    queue_size: 32
    range_max: 20.0
    range_min: 0.1
    scan_time: 0.3333
    target_frame: laser_link
    transform_tolerance: 0.01
    use_inf: true
    use_sim_time: false